### ISSUE TITLE
Homebrew Download Section

### ISSUE THREAD

**Issue by SpooneyH20** [Cruel/freeShop#10]
I'd love to make this possible, and i was wondering if i were to make a pull request if this would be something you'd be okay with me adding.

Theres a lot of neat homebrew games and utilities that can be downloaded through this app. 

I look forward to your opinion!

**Comment by Kenshii** [comment]
I would assume this is what [url=https://github.com/Repo3DS/BrewMan]BrewMan[/url] esists for

**Comment by SpooneyH20** [comment]
That's an invalid link @Kenshii

**Comment by Kenshii** [comment]
I ninja edited it. It's valid :P

**Comment by SpooneyH20** [comment]
This downloads .3dsx executables, not .cias that install to the home menu.

**Comment by Cruel** [comment]
This would be a more appropriate modification of BrewMan (which needs some updating itself).
