### ISSUE TITLE
Failed to install Content: 0xD8E08066 

### ISSUE THREAD

**Issue by ShaunDreclin** [Cruel/freeShop#100]
Getting this error when I try to install Monster Hunter Generations™ with freeShop 2.0.2:
Failed to install Content: 0xD8E08066 

Happens at the very end when it looks like it's about to finish.

Edit: Woo, issue #100 :tada:

**Comment by ShaunDreclin** [comment]
Just tried installing some games on my new 3ds, Terraria and 3D Altered Beast just failed with the same error code but Super Mario World™ installed just fine.

**Comment by Cruel** [comment]
When you retry 3D Altered Beast, does it fail every time?

**Comment by ShaunDreclin** [comment]
Tried it again and it failed again, shutdown n3ds and tried again and it worked. Going to try terraria again now

**Comment by ShaunDreclin** [comment]
Just tried terraria again and it failed with the same error code. What does that code mean, btw?

**Comment by Cruel** [comment]
When you download, does the speed ever go low? And does it ever say "Suspended" or "Waiting" or anything?

This error ever happen on your o3ds?

**Comment by ShaunDreclin** [comment]
Sometimes the download starts crawling at pretty slow speeds and randomly goes back up to full speed around 600KB/s

I first ran into the error on the o3ds trying to install monster hunter, it's pretty consistently not working. But the latest time I tried it, it's giving me "Failed: Internet problem?"

**Comment by Cruel** [comment]
This is same as #90 probably.

But if you got that internet problem message, it means the internet connection was cut out at some point and it retried and timed out ~4 times (I can't remember the default retry count).

What I need it to do is perhaps suspend all downloads when internet has this sort of problem, and then try it again in a minute or so.

**Comment by Cruel** [comment]
I'm just going to close this and defer to #90
