### ISSUE TITLE
[Suggestion] A option to skip update the freeshop

### ISSUE THREAD

**Issue by Aisasemi** [Cruel/freeShop#104]
I think that would be a great way to avoid an unknown error prevent the use of the application because we could always keep us in the last version that worked

**Comment by Cruel** [comment]
Already there. It's in update settings. Uncheck the "auto-update freeshop" box.

**Comment by Aisasemi** [comment]
Oh, I really sorry for it, i am a dumb xD, i see it now, very sorry
