### ISSUE TITLE
[Suggestion] freeshop .3dsx version

### ISSUE THREAD

**Issue by MrGb64** [Cruel/freeShop#109]
i can't install cfw, emunand., and i can't downgrade my console. but i have homemenuhax...you can make an 3dsx version of freeshop (menuhax, ninjhax, etc)?

**Comment by cheatfreak47** [comment]
No, you can't make a 3dsx version. It doesn't work like that.
freeShop only works because of CFW, without CFW it wouldn't be able to install anything.

**Comment by ihaveamac** [comment]
https://gbatemp.net/threads/wip-freeshop-open-source-eshop-clone.426573/

> **Q: Is there a 3dsx version?**
A: No, and with the elevated permissions needed, it's not worth the trouble.
