### ISSUE TITLE
No titles keys found 2.0.4

### ISSUE THREAD

**Issue by sgtstangroj** [Cruel/freeShop#111]
Hi guys,

I am getting the familiar no titles keys found message today. What do I need to do to correct this please? 

Many thanks 

SgtStangroj

**Comment by Cruel** [comment]
Like it says, you most likely need a title key files in `sdmc:/3ds/data/freeShop/keys/`

If you recently updated, your old title key file would be in `sdmc:/freeShop/` but the directory changed and you can delete that old one. Ideally, if you have a URL that has a title key file, you should go to update settings and enable auto-update for title keys, then add the URL.

**Comment by sgtstangroj** [comment]
Thanks friend- scanned the QR code and all restored. Happy days!
