### ISSUE TITLE
"Failed to finalize TMD install: 0xC8A08035"

### ISSUE THREAD

**Issue by drewthatgamer** [Cruel/freeShop#116]
I keep getting this error when installing DSiWare content, but not 3DS content.

**Comment by Cruel** [comment]
Hmm, check your available NAND space, is there enough?

**Comment by drewthatgamer** [comment]
That's why. Thanks anyways!

**Comment by drewthatgamer** [comment]
I ran out of blocks...

**Comment by Cruel** [comment]
Added error message for this code so it's less cryptic.
