### ISSUE TITLE
About the DLC

### ISSUE THREAD

**Issue by aoblue1** [Cruel/freeShop#117]
Hi im trying to download the dlc for fire emblem fates birthright but i get the0xc86044d2 error and i know it's about space on the sd card,  so it's there a way to look the size of the dlc or search for them and look the size?

**Comment by aoblue1** [comment]
Now i have enough memory to download it but ut just start then go to import and download like 2kb then just go straight to suspend and nothing else

**Comment by aoblue1** [comment]
Also keep retrying to download but go to suspend after a few seconds

**Comment by Cruel** [comment]
#37 addresses the want to see free space available.

And the download problem was fixed with #68 which will be in freeShop 2.1 (perhaps released tomorrow). The problem occurs when the connection is slow, so perhaps just try later.
