### ISSUE TITLE
Option for controlling the time until it goes to sleep

### ISSUE THREAD

**Issue by noX1609** [Cruel/freeShop#120]
Hi,

could you please implement a point in options to controll the time until the App shows Sleeping and the top display shuts of and a secound option to deactivate this function completely? Would be great :)

**Comment by Cruel** [comment]
I'll just allow disabling it. Adding configurable time isn't necessary imo.

**Comment by noX1609** [comment]
Ok great, thanks for doing this. When will a new release be made? Because i can't compile the code by myself :(

**Comment by Cruel** [comment]
Hopefully tomorrow.

**Comment by noX1609** [comment]
Ok great :)
Just for interesst: Do you know how i can compile projects like yours on Max OX? Because i only find tutorials for windows how to compire source from github and there are many libraries which habe to be manually. With the Windows Tool it's all automaticc. And is there anything else beside devKit Pro i need? 
Sorry posting this here but i don't know where else :)

**Comment by Cruel** [comment]
It mostly has linux support for building process atm, and it has a lot of dependencies. But the build process is described in the thread topic here: https://gbatemp.net/threads/wip-freeshop-open-source-eshop-clone.426573/
