### ISSUE TITLE
Crash when attempting to view/download Pokemon Alpha Sapphire

### ISSUE THREAD

**Issue by TheAntiFanboy** [Cruel/freeShop#13]
Update: Also happened when attempting to view Project X Zone™.

**Comment by TheAntiFanboy** [comment]
Also happened when attempting to download Project X Zone™.

**Comment by Filo97** [comment]
at me it works perfetcly for alpha sapphire

**Comment by Cruel** [comment]
You try restarting and trying again? This happen for anyone else?

Odd for this to only happen with specific games. Most likely it failed to fetch the information correctly and tried loading the corrupted info. It has poor error handling for these situations.
