### ISSUE TITLE
Worked yesterday before update, now after update 2.1 it crashes upon queuing

### ISSUE THREAD

**Issue by ManOrMonster** [Cruel/freeShop#136]
I was downloading fine before Freeshop updated to 2.1 today, now it crashes ("An error has occurred...") immediately after queuing any download.

**Comment by Cruel** [comment]
This happens with any game?

**Comment by ManOrMonster** [comment]
Yes, any game so far. Tried 4 or 5 different ones. No background music, not sure how to even use that. I installed Freeshop 3 days ago for the first time, used it fine that night and the next (downloaded 9 games), yesterday it upgraded and now I have the issue.

However, yesterday morning (before the update) I set it to download a few games and forgot to charge it, so the system had turned off. This was before the upgrade. Not sure if that has anything to do with the issue.

**Comment by Cruel** [comment]
That could possible have messed some things up. Can you install stuff using FBI?

**Comment by ManOrMonster** [comment]
Yes.

**Comment by ManOrMonster** [comment]
Any troubleshooting tips? I tried uninstalling (via Data Management, and deleting the freeShop folder), but when I install my original CIA it auto updates without giving me a chance to stop it.

**Comment by Cruel** [comment]
Okay, try editing your config.json and change it say `"auto-update":false`

Then install 2.0.4 (or whatever was before 2.1) and see if it works for some reason.

**Comment by ManOrMonster** [comment]
OK, I updated the config.json, uninstalled then reinstalled. Same issue. Not sure what else to do.. I've installed several games via FBI yesterday and today and they work fine.

**Comment by Cruel** [comment]
So, you tried an older version and it fails?

**Comment by ManOrMonster** [comment]
Yes, tried the originally installed CIA (2.0.4) and it's failing as well.

**Comment by Cruel** [comment]
Weird, since it used to work on that version, if I'm understanding correctly.

Did you change wifi settings since then? Perhaps change DNS to use Tubehax or something similar to block update server?

**Comment by ManOrMonster** [comment]
Oh man, I'm so sorry I wasted your time. I did indeed block update servers on my router, must have been the same day. It didn't even occur to me that it would affect freeShop. I unblocked them and it works perfectly.

Thanks for the help! And thanks so much for this incredible app.
