### ISSUE TITLE
says 1.0 in new release, also it crashes on open or will close app

### ISSUE THREAD

**Issue by mjc619** [Cruel/freeShop#15]

**Comment by mjc619** [comment]
sorry no disc, no 1.1 in bottom left only 1.0

**Comment by mjc619** [comment]
also it crashed at checking cashe

**Comment by mjc619** [comment]
yeh, it wont start at all

**Comment by mjc619** [comment]
im just going to wait until it is  morning here, yu need some sleep from yesterday, i need it too, idk how to ais in debug, but there where no problems installing so idk if it is just me

**Comment by Cruel** [comment]
Try deleting the config.json and opening it again.

**Comment by mjc619** [comment]
that fixed the first problem, i think the 2nt is a network issue, firewall may be to blame
