### ISSUE TITLE
No titles keys found 2.1.1

### ISSUE THREAD

**Issue by omikroni** [Cruel/freeShop#156]
Please, I need help with FreeShop, is showing the message: "in the title keys found.
make sure you have keys in SDMC:/ 3ds/data/Freeshop/keys/
manually copy the keys to the directory or check the settings to enter a URL to dowload the keys."

I've tried to scan the QR code and it does not work, the message "Invalid Key Format" and can not put any valid URL in the field to enter manually address. I've tried updating the cache, restart the console and has updated the " encTitleKeys.bin " by aplication in Luma 3DS.

Please help me! What might be happening? Thank you. Sry for english, i am from BR.

**Comment by omikroni** [comment]
Desculpa, consegui arrumar indo até o site https://3ds.titlekeys.com/ thanks for help.

**Comment by Cruel** [comment]
Just make sure the QR code you scan is one with an encTitleKeys.bin URL.
