### ISSUE TITLE
Latest Releases sort 

### ISSUE THREAD

**Issue by rafaga17** [Cruel/freeShop#159]
A latest releases sort would be nice so we can arrange games to appear from latest to oldest, so we can see which ones are the newest games added to this awesome app. Thanks again.

**Comment by Cruel** [comment]
This was recently handled by #146 with sorting by eShop release date.

As far as sorting by new title keys, that issues exists: #75

**Comment by rafaga17** [comment]
So this was implemented already, how do I access that kind of sort? I only get by name, size, voting, etc.

**Comment by Cruel** [comment]
It will be in next update after some more testing later today.

**Comment by rafaga17** [comment]
Oh ok, thanks again. :+1:
