### ISSUE TITLE
[Suggestion] Different, less stealy Banner modification. 

### ISSUE THREAD

**Issue by Uniiflux** [Cruel/freeShop#16]
[img]http://i.imgur.com/lQe1yfP.png[/img]

I pretty much just removed the white from the banner. Im unsure how to compile my own version of the CIA with this banned but i just figured id allow you to see it and possibly improve/use it.

**Comment by nope-dot-jpg** [comment]
Your render doesn't look right on a dark background http://i.imgur.com/1cg3F3t.png?1

**Comment by Uniiflux** [comment]
wow that does look really bad. ignore my suggestion lol

**Comment by Cruel** [comment]
Using the 3d banner anyways. Just need is modified more.
