### ISSUE TITLE
freeShop 2.1.2 Not installing any app

### ISSUE THREAD

**Issue by wg93589** [Cruel/freeShop#167]
So as the title says the freeShop doesn't want to install any app I choose. as soon as I hit download it says "Failed <App Name Here>" and when I go to the queue list I get no error message. FYI I have looked at #23 and that didn't help me.

Oh ya and also I'm using a N3DS with A9LH running Luma3DS v6.2.2 over 9.2 sysnand. My SD card is 32 GB and It has 18.88 GB left.

**Comment by Cruel** [comment]
You blocking Nintendo servers or anything on your router or DNS settings?

**Comment by wg93589** [comment]
Yes I was that I never thought of that 😶
