### ISSUE TITLE
[Suggestion] Allow download of individual DLCs

### ISSUE THREAD

**Issue by Mic1604** [Cruel/freeShop#171]
Not sure if it could be possible, but it would be particularly convenient for the HOME Menu Themes, since they are limited at 100 and they require me to delete around 155 themes individually.

Thanks in advance.

**Comment by Cruel** [comment]
Requires too much effort to add, ultimately not worth it.

I wouldn't delete them individual and instead just delete the Home Menu DLC from freeShop. Then go into Theme Shop and look at your list of owned themes and download from there individually.
