### ISSUE TITLE
Getting different error codes - failing to install after download

### ISSUE THREAD

**Issue by balloon96** [Cruel/freeShop#175]
Hello, I'm using the latest version of freeshop and encountered several problems trying to install the files.

I got 4 error codes from these respective games:
The Legend of Zelda: A Link Between Worlds - 0xD9004586
The Legend of Zelda: Triforce Heroes - 0xD8E08025
Animal Crossing: New Leaf - 0xF9608022
Luigi's Mansion: Dark Moon - 0xD8A08004

I'm running the latest version of luma3ds on EMU 11.1.0-34U with A9LH on an o3DS. SD Card seems to be working fine as I was able to install other games after encountering the error.

Right now I'm redownloading it but it might take a few hours.
Any ideas?

**Comment by Cruel** [comment]
This does seem like an SD card problem. There is diagnostic software you can run to check SD cards.

**Comment by balloon96** [comment]
That's weird since I am able to install other games just fine afterwards.
I will try to diagnose the SD card, thank you.

**Comment by balloon96** [comment]
I think I discovered the problem for error code 0xD8A08004. It happens when a download is suspended and then resumed. The download won't resume and returns the error code.

**Comment by Cruel** [comment]
Did you manage to stop the errors or try another SD card?

**Comment by gameg2l** [comment]
I was on a 4gb sd card, and I upgraded it using the emunand SD moving tutorial (which I later realized I didn't have to).
I checked the sd card with h2testw - proved there's >4gb on it for sure.
Restored my Nandmin.bin once to go back to 9,2 still can't install unsigned CIA so I upgraded it to 11.1 again to try the freeshop.
I got failed to install: 0xD9004586 on Fire Emblem Fate Birthright and Final Fantasy Explorers
then for Zelda OOT3D, I got failed to finalize 0xF9608022

Things were working fine with a downloaded OOT3D cia (which happened to be signed, I think). What else should I try aside from getting a new sd card?
If I do get a new one, do I copy these files on the current one to it?

**Comment by balloon96** [comment]
Hello, yeah it's an SD Card problem. I don't have another SD Card free at the moment, but what I did was I formatted my SD Card and copied the content back, and everything worked perfectly.

I still get errors from time to time so I have to reformat and recopy everything back when the errors occurred since one error means everything is ruined.
