### ISSUE TITLE
[Suggestion] Allow users to place a music file, for background music.

### ISSUE THREAD

**Issue by mistyhands** [Cruel/freeShop#18]
Of course, it's unnecessary and cosmetic. But I thought it'd be nice if we could, say, use the DSi shop music, or something.

Additionally, maybe have a sound effect when hovering over the icon, rather than silence? I dunno.

**Comment by Ann0ying** [comment]
lol

**Comment by maorninja** [comment]
How about an .mp3 file in `SDMC:\freeshop\` so that way we have any music rather than DSI shop music?

**Comment by poutros** [comment]
@Cruel This has been added in the latest release, right?

**Comment by Cruel** [comment]
Yeah thanks, this has been added. Though it could use some modification to make it better.
