### ISSUE TITLE
[Suggestion] Add Option to Change the Units from GB/MB to Blocks

### ISSUE THREAD

**Issue by rpalmon** [Cruel/freeShop#181]
It would be a nice feature as when you check on the storage it shows as blocks. 
Here is the conversion to help you:

1 Block = 128KB
8 Blocks = 1MB
8192 Blocks = 1GB

Or you could at least add how much storage is left directly on freeShop.

**Comment by james-d-elliott** [comment]
I would have thought it depends on the block size of the SD?

**Comment by Cruel** [comment]
I'm not going to show blocks, but there is another issue already about showing remaining space which will be added.
