### ISSUE TITLE
Nintendo Badge Arcade DLC? Also add option to see how much space we have.

### ISSUE THREAD

**Issue by rpalmon** [Cruel/freeShop#190]
Hello, can you add the ability to download the Nintendo Badge Arcade DLC for more credits?

**Comment by cheatfreak47** [comment]
That's not how it works.

**Comment by pbanj** [comment]
[not how this works](http://e.lvme.me/3risbcx.jpg)

**Comment by Cruel** [comment]
#37 addresses adding available space indicator

And if there were DLC for the Badge Arcade, it should work fine. It's not related to credits, you'll have to use cheat software for that, though you can easily be banned from using the arcade.
