### ISSUE TITLE
Failed to finalize TMD  0xD8E0806D / 0xE0E083EC

### ISSUE THREAD

**Issue by GreenBeanSupreme** [Cruel/freeShop#197]
I'm currently using an o3ds for this if it makes any difference.

I managed to download a few titles before until I started getting errors either before the install begins during the ''Installing TMD...'' portion or a failure at the end of the install with ''Failed to finalize content''.

Some of the titles on the upper screen do not load the covers, and most of them show a blank description and no screenshots.

I've checked my internet settings and overall connectivity between the 3DS and the internet connection and it's working as expected.

The SD is shown to have 63 GiB free.

Any ideas?

**Comment by DeckOfNoobs** [comment]
Which games give the errors?

**Comment by GreenBeanSupreme** [comment]
I looked into this a while ago. It seemed to be an issue with my card. I can now use Freeshop without errors.
