### ISSUE TITLE
FreeShop 2.1.3 crashes at startup

### ISSUE THREAD

**Issue by MightyBirdy** [Cruel/freeShop#198]
Same as #140 and #192, but neither reinstalling or removing /3ds/data/freeShop/cache fixes it.

https://my.mixtape.moe/clqzct.mp4

**Comment by Cruel** [comment]
Looks like it tried downloading the news during boot, I bet it failed somehow. Try deleting the news.txt in the freeShop directory and trying again.

**Comment by Blueshirtt** [comment]
Same issue on O3DSXL, Japanese region, cleared cache and deleted news.txt, same hang and crash.

**Comment by MightyBirdy** [comment]
Deleting news.txt fixed it for me.

**Comment by Cruel** [comment]
@Blueshirtt are you using any audio files for BGM?

**Comment by Blueshirtt** [comment]
Nope, fresh install on a freshly a9lh'd 3ds.

**Comment by Cruel** [comment]
Odd. Best bet is to delete the entire freeShop directory and restart it.

**Comment by Blueshirtt** [comment]
That finally worked for... whatever reason. Dunno if it was a titlekey issue on first boot or something or what.

**Comment by Cruel** [comment]
If a download fails, or is corrupted for some reason, freeShop isn't very good at handling it. But besides the cache and news there isn't any other downloaded content it loads, so that's odd.
