### ISSUE TITLE
[Suggestion] Implement Japanese input to search for games that do not have English titles

### ISSUE THREAD

**Issue by mistyhands** [Cruel/freeShop#2]

**Comment by Cruel** [comment]
I would like suggestions for a Japanese keyboard layout from Japanese users. I'm assuming hiragana/katakana would be sufficient (as long as it reduces kanji in searchable titles), but I'm not sure what preferred common layouts for that would be.

And the keyboard aside, it would need restructuring of searching code too. Worth doing in the future.

**Comment by minecast** [comment]
@Cruel Yeah, I can understand it'd be hard to program (sorry!). Although I'm not Japanese, I imagine a keyboard similar to Google's Japanese Input (1 kana as the "main" button, flick for alt kana) would suffice. Maybe a dictionary of all Japanese title names, so as you enter the name in Hiragana, it would autocomplete/provide suggestions with kana.

**Comment by nope-dot-jpg** [comment]
use this layout : http://www.famitsu.com/images/000/060/475/5405d3986d3d4.jpg
It's the best, characters are easy and intuitive to find. Even better with a dictionary.

**Comment by minecast** [comment]
Or users could enter the romaji equivalent of title names, and they'd still autocomplete.

**Comment by sonikokaruto** [comment]
Can you implement direct use of the native keyboard? if you're using a japanese 3ds it's already implemented >..>

**Comment by nope-dot-jpg** [comment]
We can have both, a japanese keyboard and a rōmaji->kana conversion (変換 button), that's how any japanese keyboard works

**Comment by Cruel** [comment]
I will not be making my own Japanese keyboard. I will instead implement the official keyboard applet. This issue will therefore be resolved by #53.
