### ISSUE TITLE
"invalid titlekeys" error although the titlekeys are correct. 

### ISSUE THREAD

**Issue by imthe666st** [Cruel/freeShop#216]
Hello,  
I'm currently experiencing an issue with freeshop.  
I dumped some legit titlekeys some time ago and they worked without any problems. However, currently whenever I try to use them freeshop downloads the game only to return an "invalid titlekeys" error. I use the encrypted titlekeys and they work on a different 3ds. I also tried deleting the 3ds/data/freeshop folder and letting freeshop create a new one.
___
Model where the error occurs: "New" Nintendo 3DS XL (european, Luma CFW)  
Model where it works: "New" Nintendo 3DS XL (japanese, Luma CFW)

**Comment by Cruel** [comment]
Couple questions:

Did you use star updater?

Do you have UNITINFO enabled in Luma settings?

**Comment by chinhodado** [comment]
Update Luma using Luma Updater, don't use Star Updater.

**Comment by Cruel** [comment]
And is UNITINFO disabled in Luma settings (when you hold SELECT during boot)?

**Comment by chinhodado** [comment]
I don't know, but I had this problem too and I was able to fix it by using Luma Updater instead of Star Updater. There's a thread about it here: https://www.reddit.com/r/3dshacks/comments/5ed1hb/psa_luma3ds_63_seems_to_break_freeshop/

**Comment by imthe666st** [comment]
Hello, 

updating Luma via Luma Updater instead of Starupdater fixed the issue. UNITINFO was disabled.
