### ISSUE TITLE
Freshop gives me this-Failed to install ticket: 0xDA08004

### ISSUE THREAD

**Issue by illest-xAsianzZ** [Cruel/freeShop#218]
I got this error after i cancelled the Home Menu themes and it froze on me the only way to get it back was to restart it. So i did just that now this error pops up. Anyway to fix this?

**Comment by Cruel** [comment]
0xDA08004 means it's an invalid ticket version. Does it happen with all titles now or just Home Menu DLC?

**Comment by illest-xAsianzZ** [comment]
It happens to all the titles now.

**Comment by Cruel** [comment]
Are you using Luma?

I would check the SD card to make sure there's no problems with it: https://3ds.guide/h2testw-(windows)

**Comment by illest-xAsianzZ** [comment]
Yes i am using a9lh and luma. Will check the sd when i get home. (What if that doesnt work?)

**Comment by illest-xAsianzZ** [comment]
ok so i had a folder which i backed up 2 days ago and i replaced all the files to go with it and now it works.
