### ISSUE TITLE
Wrong title key, even when using an auto-updated URL

### ISSUE THREAD

**Issue by NeoTechni** [Cruel/freeShop#219]
I have it running on 2 3DS's, one old, one new. Both using the same URL for the title keys. The old one works, the new one just says "wrong title key" when installation/download finishes

**Comment by Cruel** [comment]
Most likely a problem with Luma version or settings. Make sure you're using the same version of Luma (copy from working console?) and also make sure UNITINFO is disabled in Luma settings.

**Comment by NeoTechni** [comment]
It was Luma. StarUpdater wasn't actually updating it. I used a different updater and now that Luma is properly updated, Freeshop works. Thank you for that hint

**Comment by Pobega** [comment]
@NeoTechni (you should mark this bug as closed)
