### ISSUE TITLE
Doesnt work (shows white screen and upper icons freeze de app)

### ISSUE THREAD

**Issue by duducus** [Cruel/freeShop#22]
I try reinstall twice and doesnt work. Show the title search for updates and then run the app and dont show nothing.

The only button that work is the "search" one, but never finds anything. What can i do?

**Comment by Cruel** [comment]
You need a encTitleKeys.bin file in the freeShop directory on your sd card. You can get this elsewhere.

I'll change the screen so that it tells you this when no games are found. The empty window doesn't make that clear.
