### ISSUE TITLE
With waithax out, is a 3dsx version now worth the trouble?

### ISSUE THREAD

**Issue by techmouse** [Cruel/freeShop#220]
It was stated in the FAQ:

> Q: Is there a 3dsx version?
> A: No, and with the elevated permissions needed, it's not worth the trouble.

Since waithax grants elevated permissions, is it possible a 3dsx version would be worth it now? Especially for those who are having trouble getting "legit" CIAs, including the CIAs required to downgrade from 11.x?

**Comment by Cruel** [comment]
No. Having a CFW is still a requirement and probably always will be. freeShop doesn't install legit CIAs or anything comparable, it still requires sig patching from a CFW.

If anything, waithax should be used to install a CFW and then freeShop can be used.
