### ISSUE TITLE
App refuses to install any game

### ISSUE THREAD

**Issue by deadair3210** [Cruel/freeShop#23]
App was working perfectly, had a queue set up and suddenly after a few games it fails to install anything even after restarting the app and changing the game i am trying to install

**Comment by imthe666st** [comment]
How much space do you have left on your sd card, and which game do you refer to?  
Try and install something very small like 2048.

**Comment by deadair3210** [comment]
I have 20 GB free of a 64 GB card.
Found the issue, if the app is forced to close with the home menu or crashes while downloading a game, the app will fail to install anything else until the tmp dir in the app folder is removed or cleaned.

Might have the app check for the existence of the folder and either remove it or its contents on app start

**Comment by deadair3210** [comment]
Canceling a download works fine, and does not cause this issue.

**Comment by deadair3210** [comment]
False alarm, was working for a second but now is not again.
64 GB card, 20 GB free
a9lh o3DSXL running Luma3DS 5.5
console region: USA

**Comment by Cruel** [comment]
When does it fail? Does it just fail as soon as it starts installing?

**Comment by deadair3210** [comment]
It fails as soon as the game hits the queue. The download notification and the failed notification stack on top of each other in most cases

**Comment by Cruel** [comment]
Hmm, probably won't be able to help you until I add better error messages.

But I know installs instantly fail when there's no internet connection. I would guess it's an internet related problem.

**Comment by deadair3210** [comment]
I have tried it with multiple networks at multiple locations. I very much doubt its a network problem

**Comment by deadair3210** [comment]
I have done some bug testing, it doesnt seem to be a network issue or a space issue. I have 30+ GB free on my SD card and it seems to have the same issue regardless of how much room is available. Network doesn't seem to be the issue either as I have tried it in multiple locations with the same results

Is there any way I can help figure out the issue? Like testing a build or something. I have a9lh so I am not really worried about anything special as long as I can recover

**Comment by Cruel** [comment]
Next build will include few more installation errors that may help. Will probably be released tomorrow.

**Comment by deadair3210** [comment]
Ok, when you release it, I will update this issue with the changes if any

**Comment by RenaKunisaki** [comment]
Same problem here. It seems like I can download any game before Donkey Kong Country on the list. DKC and any games after it will fail as soon as they try to download. Deleting tmp, cache, and config.json didn't help. SD card has ~10GB free out of 16GB total.

Likely somehow related is the fact that I queued the game immediately before Donkey Kong Country, then (realizing it's just a preview video) cancelled it before it started downloading. Once current downloads finished, Donkey Kong Country and everything after it in the queue instantly failed to download.

Perhaps it's an issue with encTitleKeys.bin? Redownloading that didn't help either, though.

**Comment by RenaKunisaki** [comment]
OK, so turns out I'm dumb, Donkey Kong Country is New 3DS only. So the problems are just:

- No indication if a game is playable on o3DS
- If trying to download SNES VC games on o3DS, everything queued after them will also fail

**Comment by deadair3210** [comment]
My problem doesnt seem to be the same as yours, though Im glad you figured it out.

@Cruel I'm about to build the program from source and see if that helps any,if i can figure out how to set up a build env on Ubuntu 16

**Comment by deadair3210** [comment]
I cant seem to get a build env working correctly, so looks like im just going to have to wait until the next build.

**Comment by deadair3210** [comment]
Latest release seems to have fixed it, closing. Will reopen if issue reappears
