### ISSUE TITLE
Black Screen Mid Install

### ISSUE THREAD

**Issue by fallenlucario** [Cruel/freeShop#28]
While downloading/installing Pokemon Rumble World, the screen goes black. Not sure why, I've downloaded/installed other things. This just make the screen shut off. I can still hear sound and press home to return to the home menu with the screens being black though.

**Comment by Cruel** [comment]
This happens after 30 seconds of inactivity. Pressing a button should turn the screen back on. Pressing the home button should turn the screen lights back on, that was fixed in 0df1ebb9 and will be in 1.2

**Comment by fallenlucario** [comment]
Ah okay, thank you, pressing home didn't do so on the version I was on, but glad to know it is fixed in the future!

**Comment by Cruel** [comment]
Bottom screen visible currently since 1f47b230c

FWIW, sleeping will be optional in setting page eventually.
