### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by rpalmon** [Cruel/freeShop#29]
I am unable to install this .CIA file using FBI or NASA. Can you make this like the homebrew application Brewman where you launch it from the homebrew launcher? It would be great! That way I wouldn't have to install it using FBI and get an error.

**Comment by deadair3210** [comment]
anything launched by the homebrew launcher is unable to install anything in a CIA, as they do not have the necessary permissions

The only things that can install cia's are eshop, system update, and cia installers like FBI

**Comment by rpalmon** [comment]
How about making it so we can get the ticket file to be able to redownload it from the eShop? That way we won't worry about the .CIA file.

**Comment by deadair3210** [comment]
The most that would be able to be done is to download the tik and put it in a folder for later install with something like FBI
3dsx apps dont have the ability to access anything more than a normal game would be able to do, so anything more complicated than downloading a file is usually out of the question

**Comment by Cruel** [comment]
I will not bother making a 3dsx build of freeShop. There are permission problems I prefer not to deal with. Additionally, you need a CFW to utilize what freeShop installs, so I don't see the point of a 3dsx build.

Do you not have a CFW? That would be why it's failing.
