### ISSUE TITLE
Monster Hunter 4 Ultimate always gives a "Failed?" error message at download completion

### ISSUE THREAD

**Issue by TheAntiFanboy** [Cruel/freeShop#30]
Almost every other game I've attempted to download appears to work just fine.

**Comment by Cruel** [comment]
If it happens at the end during finalizing, it's usually due to a bad ticket.

freeShop 1.1 was supposed to delete old tickets, but there was a bug. You can either delete the ticket yourself using FBI and try again, or wait until freeShop 1.2 (in a day or two) and try then.

**Comment by TheAntiFanboy** [comment]
Where are the tickets usually stored?

**Comment by dirtylittlehindu** [comment]
I am also having this problem i wait till 1.2 and that did not help it failed at around 99.8% still. can someone give me directions on how to delete the old tickets.

**Comment by Cruel** [comment]
Did it give you an error message?

1.2 deletes the tickets (or at least it should), so that's probably not the problem I guess...

I'm now guessing it's some sort of corruption during download. That can be minimized by avoiding reordering the queue, but ultimately there are just http bugs I need to fix. This happens with smaller games too, but with larger downloads the odds of something going wrong increases.

**Comment by dirtylittlehindu** [comment]
I found out what was wrong it was something else on my sd card that did like freeshop but thank you for the quick responses also love that u for making FreeShop

**Comment by Hyperom** [comment]
Ive had this same problem with MH4 and Donkey Kong Country Returns

**Comment by floatiepen** [comment]
I got this error repeatedly from Bravely Default (even on 1.2.1 today).  After deleting the ticket through FBI it worked, so maybe the ticket isn't always getting deleted prior to the download?

failed to install content 0xD8E08066

**Comment by Cruel** [comment]
@floatiepen When you say "it worked" you don't mean that freeShop successfully installed Bravely Default, do you? Because I believe I found an error that make it so games over 2GB don't install properly. I just fixed it and I'm downloading MH4U right now to test.

**Comment by floatiepen** [comment]
@Cruel  Oh yeah, it definitely did install Bravely Default.  There were a couple other large games that often had errors that I eventually got through too (DKCReturns, maybe something else?).  Could it be an intermittent thing?

**Comment by Cruel** [comment]
Hmm, did the download ever suspend and resume when you did it? I think the bug could be bypassed if you were to reorder the queue (or something similar) so it resumed somewhere before the 2GB limit.

**Comment by floatiepen** [comment]
Oh, yes.  I definitely did some of that.  I moved a couple smaller entries to the top of the list, and they paused the larger download while they completed.  I remember wishing I had the option to move it to the second spot so as not to interrupt the download currently in progress, but it sounds like it actually opened the way :D

**Comment by Cruel** [comment]
Ok good. Glad to finally get this figured out.
