### ISSUE TITLE
[Feature request] Bandwidth throttling

### ISSUE THREAD

**Issue by LisandraBrave** [Cruel/freeShop#31]
Perhaps some way to set it up so you can set a upper limit on how much bandwidth you can use at once.

**Comment by chinhodado** [comment]
Not sure how useful this is tbh.

**Comment by LisandraBrave** [comment]
Consider when you're trying to do something at the same time freeshop is downloading. Right now, it'll use any available bandwidth, and if you're on a shitty connection, all your other devices will run like shit.

**Comment by Cruel** [comment]
This will probably require more effort to do than it's worth. For now, it's not going to be added.
