### ISSUE TITLE
[Suggestion] Autoupdater

### ISSUE THREAD

**Issue by lukecamilo** [Cruel/freeShop#32]
How about an autoupdater? or at least a quick check to compare the last version published on github, just to see if we're updated

**Comment by chinhodado** [comment]
That feature is already available...

**Comment by poutros** [comment]
It auto checks for updates on startup and installs them.

**Comment by lukecamilo** [comment]
I didn't know that, i never realized it had autoupdate. It wasn't on the features list so i figured it wasn't implemented. Closing this issue now. Thanks!

**Comment by Cruel** [comment]
Just pushed a new release. You can try running freeShop now to see the auto-updater work.

**Comment by lukecamilo** [comment]
Yeah i just saw it, thanks a lot!
