### ISSUE TITLE
[Suggestion] Themes 

### ISSUE THREAD

**Issue by lukecamilo** [Cruel/freeShop#33]
Would it be possible to download and install official themes? I don't really know if they're published in the same way as games, but if they are it would be a nice upgrade

**Comment by Cruel** [comment]
Yeah, there are some themes that can be installed. Though before figuring that out, I'm going to be adding updates/DLC.

**Comment by lukecamilo** [comment]
Milestone for 1.4 maybe? :yum:

**Comment by Cruel** [comment]
Will handle with soon with #20 as a part of freeShop 1.3

Themes are essentially DLC for the Home Menu, so they're lumped together with the work needed to implement DLC.

**Comment by lukecamilo** [comment]
DLC's been implemented, but Themes hasn't. 
Is it ok to reopen this issue or do you need me to open a new one? 

Thanks for all the hard work!

**Comment by Cruel** [comment]
I made an issue for it with #88
