### ISSUE TITLE
Issue when closing system while app is downloading a queue

### ISSUE THREAD

**Issue by deadair3210** [Cruel/freeShop#36]
If the system is closed while the app is open and downloading games, the downloads in the queue will fail immediately after the app resumes

**Comment by Cruel** [comment]
Closed meaning into sleep mode?

**Comment by deadair3210** [comment]
Yes, closed as in sleep mode.

**Comment by deadair3210** [comment]
Not sure if related, but after removing the queue file so the app would recreate it, the app refused to recognize the enctitlekey file until i completely deleted the entire freeshop folder from the sd card and let it recreate it

**Comment by Cruel** [comment]
Fixed in e7e81d5a and will be in next release.
