### ISSUE TITLE
[Suggestion] Modification of the current banner

### ISSUE THREAD

**Issue by Noroxuz** [Cruel/freeShop#4]
Having seen the current banner I felt it is indeed pretty lacking, so I thought of adding my own version!
I would greatly appreciate if you would add it to your work :+1: 
It is a modified version of the eShop banner.

![20160531_012959](https://cloud.githubusercontent.com/assets/19223583/15659691/60e4376e-26cf-11e6-9727-f380cfa26226.jpg)

You can get it from here: 
https://mega.nz/#!1Z9RxR6R!L1eKjp9M_B10OOjYI8uyT_Ls1sqzqc66Yf46I1rFiBU

Sorry, that I am linking stuff on github, but I have no idea how to replace your 2D banner with a 3D banner after forking '<_'

I'll remove the link after I figure out how to fork properly...

EDIT: Added fixed version of the banner.

**Comment by Cruel** [comment]
It indeed needs a better banner, and I like this one. But I have to be careful about using potentially copyrighted things. This may be considered a Fair Use modification, I'll look into it, thanks.

**Comment by Noroxuz** [comment]
I am happy that you like it! :)

Concerning the copyright issues I can only say that the GBAVC Inject tool, which is used for injecting ROMs into a VC game also uses Nintendo assets and never had any problems with copyright infringement. This led me to believe that the banners are not copyrighted material per se.

Of course, I might be wrong aswell, but the GBAVC Toolset has been around for ages ¯\_(ツ)_/¯

**Comment by mistyhands** [comment]
IMO, if Nintendo were concerned about use of their assets in Homebrew banners this much, they would also put a lot more effort into eliminating online distribution of any homebrew.

**Comment by Cruel** [comment]
Are you able to make either the text or the bags black? (preferably both)

I will use it if one of those can change, otherwise it's too similar.

**Comment by Noroxuz** [comment]
I can change the text color to black easily, however the bag color changes to brown when all textures are painted black. 
Probably something you would have to edit with HxD.

How about making the bag color blue?

**Comment by Cruel** [comment]
I like the text. How do the bags look white?

**Comment by Noroxuz** [comment]
I tried white and the light effects of the banner caused an orange colorshift. It didnt look good at all.
However after applying grey to the banner it now appears white-beige/yellow-beige. Pure grey/white will probably not work as the model mixes orange into applied colors. 
https://mega.nz/#!8F8lHICJ!kfG6CNB06tbDROrDKfRAMwQOFP90WuFka7yKdMU3c-I

![20160601_000557](https://cloud.githubusercontent.com/assets/19223583/15692113/f01720f0-278c-11e6-9b77-d43ff75c5bab.jpg)

It is not pure white, because of the changing light effects.
Doesnt look too bad though

**Comment by Cruel** [comment]
Thanks, I'll give these a try a little later.

**Comment by Cruel** [comment]
Okay, I tried them. I think the "black" bags fit in the best, even if they appear brown, since the icon/theme includes a black bag.

Other than that, the text has a couple problems:

- The freeShop text outline is a bit blurry and thin. You can use the eShop banner for comparison.
- The font is a bit off, primarily the "e" looks weird

I'm not sure what size you have it at for scale, but I think it would be best if you use [this image](https://i.imgur.com/teS1eBP.png) and cropped/scaled it and applied stroke until it looked good.

Or here's one with stroke you can crop and scale to see how it looks: https://i.imgur.com/VljLxOM.png

**Comment by Cruel** [comment]
Also, use this audio: https://github.com/Cruel/freeShop/blob/master/res/app/banner.wav

Thanks.

**Comment by Noroxuz** [comment]
Done! 
https://mega.nz/#!EQlWiDJL!151SaZS1v-JEvbBxgkc6F16e36PyyZP2wAhOJ00Pt90

Please tell me if you want anything else changed :)

**Comment by Cruel** [comment]
Hmm yeah, I tried with higher screen brightness and it's too brown. Text is probably fine though.

Have you already tried to just get the darkest grey you could? What does a color like [rgb(0x0, 0x3c, 0x5a)](http://www.color-hex.com/color/003c5a) look like?

**Comment by Noroxuz** [comment]
https://mega.nz/#!9ZFXhLSS!o3dOW4o-LQXFWQ7Qd-WJk8ux68fsyaceTffwALLE7XM
I gotta say the (0,60,90) blue looks surprisingly good.
![20160604_011754](https://cloud.githubusercontent.com/assets/19223583/15795518/7f7ae3b4-29f2-11e6-8ddf-402f9f504e0d.jpg)
Changing the color to dark grey only brightens up the brown... This blue color seems to be perfect imo

**Comment by Cruel** [comment]
Yeah, that'll work, thanks. I'll add it for the next update.

**Comment by Elizafox** [comment]
There's probably no copyright issues btw, because the [https://en.wikipedia.org/wiki/Threshold_of_originality threshold of originality] has not been met on Nintendo's eShop logo. You may have trademark issues though.
