### ISSUE TITLE
[Suggestion] Download demos

### ISSUE THREAD

**Issue by thejsa** [Cruel/freeShop#41]
It'd be nice to be able to download demos - if nothing else, it's quicker (and takes less storage space) to download a demo to try out a game before downloading the full version.

**Comment by Sychopath52** [comment]
you already can

**Comment by thejsa** [comment]
@Sychopath52
No, you can't; special demos are available as they are listed as separate applications on the eShop, but I mean standard demos, eg. for Sonic Lost World

**Comment by Cruel** [comment]
They'll be added along with Updates/DLC, all them kinda go together when implemented so it's no additional work.
