### ISSUE TITLE
Failed to add Seed: XXXXX

### ISSUE THREAD

**Issue by maxiking913** [Cruel/freeShop#42]
Every Game i want to download says failed to add Seed.

 N3DS 9.2.0-20E
Luma,Pasta Cakes testes none work

**Comment by Cruel** [comment]
Hmm, seeds were introduced in 9.6 so I would guess that's the problem, but I'm surprised nobody has mentioned this before. If other people on < 9.6 can confirm, then I'll add some sort of FW check.

**Comment by maxiking913** [comment]
so i need emunand?

**Comment by maxiking913** [comment]
confirmed, now on emunand 11.0.3. Tried with o3ds too, downgradet to 9.2 Doesnt work. Upgradet emunand again, same as new one. Min firmware is 9.6

**Comment by Cruel** [comment]
Well, it shouldn't fail with all games, though. Most games don't use seed. You're still able to download those, right?

**Comment by maxiking913** [comment]
Reinstalled 9.2 for you. Nope it failed on every single game, even games that dont have seeds. Idk why. Ancl, zelda and super mario 3d land. Failes to add seed even when they r no seed games

**Comment by maxiking913** [comment]
Some little games work. Like u said 2048 or animie channel. But "big" games (gbc emu games too) pokemon red version.
Nearly everthing fails under 9.6

**Comment by maxiking913** [comment]
Also would be cool if we can download dlc with that.

**Comment by Cruel** [comment]
I just checked, and Pokemon Red Version was released on eShop 2016-02-27 has a crypto seed. It has to do with how old they are, not how "big" or anything. For example, you can install Bravely Default, but Bravely Second would fail.

Anyways, I'll be adding DLC/Updates/Demos soon, probably in next update.
