### ISSUE TITLE
Downloading latest cache: r7……

### ISSUE THREAD

**Issue by franciszhu** [Cruel/freeShop#43]
when I launch the program, it freeze on the screen which shows "Downloading latest cache: r7……"

**Comment by Cruel** [comment]
Does the loading icon still move? Or is it completely frozen?

Sounds like an internet issue, and I haven't added a way for it to retry on failure. Does it still have even after rebooting your console?

**Comment by WeAreAllMadeOfStars** [comment]
Same problem on 2 units at the moment (n3DS XL and o3DS XL, both A9LH + Luma3DS by Plailect's guide). To reproduce:
1. freeShop 1.2.1 in a good state.
2. Delete /freeShop/.
3. Uninstall freeShop 1.2.1 via System Settings.
4. Install freeShop 1.2.2.
5. Run encTitleKeysUpdater.v1.2.1, download.
6. Start freeShop 1.2.2
7. "Downloading latest cache: r7……". Icon is moving, orange LED blinking each 6-10 seconds. Trying to termintate after HOME button leads to "Program is closing" (or something like that, I don't use English locale) on the lower screen till power off via Power button.

**Comment by Cruel** [comment]
If you install freeShop 1.2.1 and run it, will it download and install freeShop 1.2.2 for you? Both updating mechanisms are the same, so I'm curious if that fails for you too.

**Comment by WeAreAllMadeOfStars** [comment]
freeShop 1.2.1 goes to an infinite loop as well, but not on a cache stage: "Updating freeShop 1.2.2 ...". Have tried to put it to sleep mode: after the first close animation has stopped, after second one - black screens until power off with long Power press. Maybe it has something to do with "Add basic waits for http/wifi interrupts" commit?

**Comment by Cruel** [comment]
Okay, so it's clearly not a cache download problem, but a download problem in general. Have you managed to use freeShop and download a game? Or have you never progressed past the cache downloading?

**Comment by WeAreAllMadeOfStars** [comment]
I've updated freeShop to 1.2.1 yesterday with clean-install (delete from System Settings and remove /freeShop/) and was able to run it and browse games, but haven't tried to install one. 

Today I've tried to clean-install 1.2.2 and encountered "Downloading latest cache: r7 ...". Then I've clean-installed 1.2.1 and it's "Updating freeShop 1.2.2 ...".

**Comment by Cruel** [comment]
Have you messed with your internet settings at all (e.g. DNS settings)?

**Comment by WeAreAllMadeOfStars** [comment]
No, I didn't. Good news: I've managed to successfully run 1.2.2. on both units right now. So as for me, it was some server issue. Thanks for the app!
