### ISSUE TITLE
[Suggestion] Allow uninstallation of titles from the app

### ISSUE THREAD

**Issue by Elizafox** [Cruel/freeShop#44]
Instead of mucking around system settings, it would be really convenient to have an interface that allowed titles to be uninstalled by the app itself (this is something I think the eShop itself should do, but doesn't).

**Comment by deadair3210** [comment]
+1

**Comment by thejsa** [comment]
I think it would be good if it had an option to uninstall the ticket, too, in case you want to buy something legit that you pirated.

**Comment by Cruel** [comment]
Added in latest release.
