### ISSUE TITLE
Auto download of encTitleKeys.bin

### ISSUE THREAD

**Issue by poutros** [Cruel/freeShop#5]

**Comment by Cruel** [comment]
This would be convenient (and it's easy to code), but poses possibly legal problems. I will likely just include a feature where you can specify URLs to titlekey bins and it will auto-fetch it in the beginning with everything else. That way nothing is including by default.

**Comment by poutros** [comment]
That would be fine as long as the website is saved in the config.

**Comment by Noroxuz** [comment]
CIAngel also appears to ask you if you want to download the JSON file with confidential information, so I think this might be possible without posing legal threats.
I'd ask cearp/drakia for information on how they handle this

**Comment by Cruel** [comment]
I think they just don't care as much about the legal issue. Don't know, perhaps I'm being too cautious.

**Comment by TheDgtl** [comment]
For CIAngel, we're just taking on that risk ourselves. I doubt anything will come of it, but it does open us up to issues (Well, me atleast, cearp probably not so much as he's not in Canada/USA)

**Comment by ElyosOfTheAbyss** [comment]
What if you add a feature people can paste a link to the .bin into a .txt file in the freeshop folder and whenever it need's to be updated they go into settings and tap "Update encTitleKeys.bin" or something like that

**Comment by leag** [comment]
@MatMaf did encTitleKeys.bin-Updater

**Comment by MrJPGames** [comment]
It would be nice if it also read the title keys installed to the console. Allowing you to use the freeshop for games you actually purchased in the eShop.

**Comment by Cruel** [comment]
@MrJPGames That's the plan, to allow for it to work with any encTitleKeys.bin but I won't add that until it's a bit more stable.

As for this issue, I don't currently plan on auto-downloading any titlekeys. My mind could change, but I'm closing this for now.
