### ISSUE TITLE
Sortable by region / file size / name / ...

### ISSUE THREAD

**Issue by JHGitty** [Cruel/freeShop#51]
We need sort features:
- by region
- by file size
- by name

**Comment by lex3a** [comment]
Also 

- by genre.

**Comment by Cruel** [comment]
Genre (and region) will be in filter and not sorting option. Doesn't make much sense to sort by categories like that, you usually sort by values that are unique to each title.

Worked on sorting stuff yesterday. It will have this:

![sorting image](https://i.imgur.com/E9MccG1.png)

**Comment by lex3a** [comment]
Wow! 
It looks very good!

Also, a bit offtopic, but is it possible to parse prices and add "BUY" button? This button will open game in official eShop, where you can buy it. 
Is it even possible to launch eShop with parameters?

**Comment by Cruel** [comment]
I've tried something similar before and it didn't quite work out. But there have been recent changes in ctrulib that perhaps could help do it. I added issue #64 so I don't forget to look into it.
