### ISSUE TITLE
Larger games fail at end of install.

### ISSUE THREAD

**Issue by phantomdenied** [Cruel/freeShop#58]
Ive attempted to install a few games that are above .5 gig and the constantly fail. Smaller games Download/install no problem. 

Example:
Legend of Zelda Majoras Mask 3D
Failed o finalize content install: 0xD8e08025

Retrying again to see if I get the same Hex

**Comment by phantomdenied** [comment]
Retried, Failed at same address.

**Comment by phantomdenied** [comment]
Different title, same fail message.

**Comment by Cruel** [comment]
What CFW are you using?

**Comment by phantomdenied** [comment]
I followed Plailects guide using OOT as an entrypoint on N3ds.

**Comment by Cruel** [comment]
So are you using Luma3DS?

**Comment by phantomdenied** [comment]
Yes.

**Comment by Cruel** [comment]
Perhaps try another SD card, I don't think it's a freeShop problem.
