### ISSUE TITLE
I can´t install freeShop

### ISSUE THREAD

**Issue by Totellini** [Cruel/freeShop#59]
When i try to install freeShop i always get a Error it says:
Result code: 0xD8E0806A
Level: Permanent (27)
Summary: Invaild argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)

i´m on 10.5
and i created a freeShop folder with the encTitleKeys.bin file and the cia is the currently the newest version.

**Comment by Cruel** [comment]
You need a CFW (like Luma3DS). Are you using one?

**Comment by Totellini** [comment]
No

**Comment by Totellini** [comment]
I have a question can you send me something like a guide to install it?

**Comment by cheatfreak47** [comment]
https://github.com/Plailect/Guide/wiki Read up.

**Comment by Totellini** [comment]
Thank You Very Much c:

**Comment by rpalmon** [comment]
Can you send me a guide to install Luma3DS on v11.0?

**Comment by cheatfreak47** [comment]
@rpalmon You can't do any non-userland (eg. CFW, FreeShop, FBI, Decrypt9, etc.) hacking on Stock 11.0.0 consoles unless you use a hardmod. (ie, taking the 3DS apart, and soldering some wires to specific pads on the board and attaching an SD card reader to them, allowing you to dump the nand directly) 

With a hardmod it's possible to perform a physical based attack abusing a flaw in the system that allows us to do minor downgrades to the native_firm.
