### ISSUE TITLE
Add enctitlekeys updater

### ISSUE THREAD

**Issue by tatundria** [Cruel/freeShop#63]
Is it possible to add the option to automatically download enctitlekeys.bin when you load this app? Like enctitlekeys updater does...

**Comment by Cruel** [comment]
It's not legal to share keys, so I'm not including anything that auto-fetches shared keys.

Instead I will add an option in the settings pages where you can specify URL(s) to fetch on load. This will essentially auto-update any titlekey file stored remotely.

**Comment by tatundria** [comment]
Great! Thank you!
