### ISSUE TITLE
Save filter/sorting options

### ISSUE THREAD

**Issue by hemmy** [Cruel/freeShop#65]
save the filter/sorting setting, thx!!

**Comment by hemmy** [comment]
Some of the people like me, I will prefer only 3DS game installed in my console and not dsiware or other. Filter feature actually provide a good environment to do so. But in order to avoid my kid install such things, save the last setting(or passlock) will be a good idea.

**Comment by jamesyc** [comment]
This seems to be the only feature milestone missing from an 2.0 release. 

Exporting saved settings seems to be a bit pointless, eShop doesn't do that either; it would also be complicated to design. However, adding a PIN lock option to the settings menu for childproofing might be a good idea.

**Comment by Cruel** [comment]
I'll probably add a save/clear button to filter/sorting pages. I think it's ideal to require users to manually save current filter than having it automatically save every time it's changed.
