### ISSUE TITLE
cannot found "encTitleKeys.bin" after update to the 1.2.2

### ISSUE THREAD

**Issue by FlynnYork** [Cruel/freeShop#69]
Error:
"No title keys found.
Make sure you have encTitleKeys.bin in your sdmc:/freeShop/ directory."

it's working right before 1.2.2. 
and I sure that encTitleKeys.bin was included in my sdmc:/freeShop/ directory.
1, used differents and re-format sd card are not working now. ;(
2, although i try encTitleKeys updater still not working.

**Comment by Cruel** [comment]
I've never been able to duplicate this issue. Try this and tell me if it works:

1. Delete freeShop dir from SD card

2. Open freeShop (it creates the directory(s) itself)

3. Close freeShop after it tells you that you need the titlekey file.

4. Manually copy the encTitleKeys.bin into the dir (or use the updater homebrew)

5. Run again.

**Comment by FlynnYork** [comment]
try again,(use updater or manual update the encTitleKeys.bin) still not working
systrem: A9LH+luma CFW. has been open region language free.
(restored the A9LH Sysnand before using freeshop.)

**Comment by Cruel** [comment]
What file system is the SD card, and what did you format it with?

**Comment by FlynnYork** [comment]
FAT32-16kilobytes, 
Windows 7 64bit system default format option.

**Comment by Cruel** [comment]
Then I have no idea how to fix it right now. I've seen a few people have the same problem, but they eventually fixed it somehow.

**Comment by FlynnYork** [comment]
Yeah. i'll be write msg. if I figure out it. ;D

**Comment by FlynnYork** [comment]
The reason is network lag. (cannot received the data.json and image files, may be you can wirte this tips on the error screen.)
then,
Using PC's WiFi which has been connected to the proxy server.
Thanks your help. :+1:

**Comment by Cruel** [comment]
When you deleted the folder and opened freeShop again, did it not download the cache? Or did it somehow skip that part?

**Comment by FlynnYork** [comment]
1, Deleted the folder and opened freeShop again, I can see it's working right now, there is "Extracting latest cache..." was showed on screen.  Of course, still show the no title keys found. 
2, It's working after copy the encTitlekeys.bin to sdmc:/freeShop folder.

**Comment by Cruel** [comment]
Ok makes sense. I guess somehow the cache got deleted before.
