### ISSUE TITLE
Show what games are already installed to prevent reinstallation or just hide them

### ISSUE THREAD

**Issue by poutros** [Cruel/freeShop#7]

**Comment by Timzem** [comment]
+1
Installing from freeshop over cia installed backup removes save files of that game. 
(Removed my mh4u save after accidentally pressing "x" when title was selected in freeshop. Very sad :( )

**Comment by t1mz** [comment]
+1
Installing from freeshop over already installed cia backup _removes save files_ of that game.
(Removed my MH4U save after accidentally pressing "x" while it was selected in freeshop. Very sad :( )

**Comment by JHGitty** [comment]
+1

**Comment by maorninja** [comment]
Just hiding them would be better. Also, please don't spam +1 and just put the thumbs up icon on @poutros because scrolling through long text is annoying.

**Comment by Cruel** [comment]
Handled this in @e7d4dad and some other recent changes.
