### ISSUE TITLE
Failed to Finalize Content Install

### ISSUE THREAD

**Issue by 1102085a** [Cruel/freeShop#70]
As the title says, I'm getting titles fully download on v1.2.2, only to say "Failed to finalize content install:" followed by an 0x code, like '0xD8E08025'. I'm not sure what's causing this, and smaller titled seem to download just fine, it seems to only have with larger games over 1GB

**Comment by Cruel** [comment]
Try installing the game(s) that fail with FBI or something else. Let me know if they work. Last time I saw this error it was an SD card issue, so I just want to make sure it's not that.

**Comment by 1102085a** [comment]
After having more problems and restoring from a backup after format, I think it might have been an SD card problem.
