### ISSUE TITLE
Cant download anything: Failed to add seed

### ISSUE THREAD

**Issue by Sammy-22** [Cruel/freeShop#71]
Today i opened up the free shop, and it had some cache update or something. And tried to download Hyrule warriors and i got an error saying "failed to add seed" tried downloading some other games and got the same error message

**Comment by Cruel** [comment]
Many game require minimum FW 9.6, I'm guessing you're using something less than that?

**Comment by Sammy-22** [comment]
how do i check. im a noob with all of this, coz i got my friend to do the hack for me. All i know is that the version of my 3ds is 9.2.0-20E

**Comment by Cruel** [comment]
Yeah, you're on 9.2 so many newer games (released in last year) won't work, but there should still be plenty that do. There are many guides for how to safely upgrade and such, I can't cover that topic myself.
