### ISSUE TITLE
 Failed to finalize TMD install: 0xC86044D2

### ISSUE THREAD

**Issue by kugoyami** [Cruel/freeShop#77]
I already downloaded a few games (Pokémon X, terraria, and Mario Kart 7), however when I try to install Super Smash Bros. or The Legend Zelda: A link between worlds, It gives me this message:  Failed to finalize TMD install: 0xC86044D2, Pls fix, other than that, thank you for this great app!

**Comment by Cruel** [comment]
I believe that means SD is full. Check it and confirm.

Still gotta add capacity checks in freeShop

**Comment by takeshineale128** [comment]
Can confirm that Failed to finalise TMD install: 0xC86044D2 error does mean the sd card is full or not enough space.

**Comment by kugoyami** [comment]
Yup, the SD cart was too full, I purchased a 16gb card, and it works fine now, thanks.
