### ISSUE TITLE
Program hangs when pressing A on a title while in the settings tab

### ISSUE THREAD

**Issue by danieljg** [Cruel/freeShop#78]
Using 2.0

**Comment by Cruel** [comment]
Annoying lol. I'll have to issue a bug fix update since this is pretty big.

**Comment by danieljg** [comment]
If this happened while a download was going on, should the cache be cleared or something?

**Comment by Cruel** [comment]
No. It'll either restore the queue or not. The system will automatically clean up in incomplete installs.

**Comment by Hyperom** [comment]
Damn, that was quick

**Comment by danieljg** [comment]
Nice, I'll update later today.
