### ISSUE TITLE
Crash when DLC or Update is done installing

### ISSUE THREAD

**Issue by cheatfreak47** [Cruel/freeShop#82]
With the latest Freeshop 2.0.1, I'm getting crashes any time I finish installing updates or DLC. 
It forces a reboot of the system too.

I tried wiping all my settings and caches but it still continues to do so.

I have a loooot of titles installed, could that be the issue?

**Comment by THEDARKK** [comment]
Hello ,
Same
Also, the filter is never save.

**Comment by deadair3210** [comment]
I have had this happen once when installing some dlc.

**Comment by ChlorideCull** [comment]
I found that I never managed to trigger a crash if I queued a DLC install, let it finish, and then restarted freeShop. It always triggers a crash when attempting to install something *after* having installed DLC.

**Comment by Cruel** [comment]
There are a lot of people having this issue, I'll have to test updates/DLC more.

Are there no updates or DLC that have worked for you? And what is your CFW / console?

**Comment by THEDARKK** [comment]
NEW 3DS 11.0 arm9loaderhax LUMA 6

**Comment by Cruel** [comment]
Is this what happens? https://www.youtube.com/watch?v=nkPTS9BSf5I

**Comment by THEDARKK** [comment]
Yes same.

**Comment by Kevman323** [comment]
I'm having the same issue

**Comment by Cruel** [comment]
Do you guys have a lot of titles installed? I wonder if it's related to the install list taking a long time to refresh.

**Comment by Kevman323** [comment]
I have ~80 game icons on my home menu. ~55 are eshop games.

**Comment by Cruel** [comment]
I was able to duplicate this. I should have this fixed later today (along with a few other bug fixes).

**Comment by deadair3210** [comment]
I have a 64 Gb SD card full of games, so its safe to say that I have a lot of titles

**Comment by THEDARKK** [comment]
It is possible to save the fitrages of free shop?

**Comment by Cruel** [comment]
Filters don't save yet, they will eventually though.

**Comment by Cruel** [comment]
Please test 2.0.2 to see if this is fixed.

**Comment by tombomb** [comment]
im still crashing on DLC install, on version 2.0.2, any logs or anything I can grab you?

**Comment by Cruel** [comment]
@tombomb There was a separate bug when game list was open after completion. Let me know if it still happens with 2.0.3

**Comment by AgentScarlet** [comment]
I got some titles but not sure of amount. maybe like 12 or so. it keeps crashing on me too. I'm on old 3ds with a9lh/luma btw.  I was wanting to dl a new game to try it out better than playing a demo and still aint sur if ya like it. lol. anyways I hope someone can help

**Comment by Cruel** [comment]
Can't help without more details. Need to know how/when exactly it crashes.
