### ISSUE TITLE
Add HTTP timeout to settings

### ISSUE THREAD

**Issue by ThevishGeko07** [Cruel/freeShop#83]
Hi, I was just going to download a few games and I can't access the shop anymore. It just says Installing freeShop 2.0.1 and is completely frozen. If you need it I'm running EUR N3ds with ReiNand 11.0

**Comment by poutros** [comment]
Uninstall freeshop. Install the latest version again. See if it works.

**Comment by Cruel** [comment]
So even the spinning indicator on the bottom screen was frozen?

**Comment by ThevishGeko07** [comment]
Yes. It would lauch and spin for about 30 seconds then freeze. The only way out is a hard reset

**Comment by ThevishGeko07** [comment]
I uninstalled and updated with the new .cia and it boots, but whenever i try to download something above 1kb it will keep saying retrying then Error:Internet Issue?

**Comment by Cruel** [comment]
I see. It probably kept failing and retrying during update too, that's why it crashed.

Do you have slow internet? I may need to adjust the timeout/retry values.

**Comment by ThevishGeko07** [comment]
I uninstalled and updated with the new .cia and it boots, but whenever i try to download something above 1kb it will keep saying retrying then Error:Internet Issue?

**Comment by ThevishGeko07** [comment]
Yeah I have the slowest Internet in existance (I really shouldn't be downloading 2 gig games). The odd thing is that 2.0 downloaded perfectly fine to start off with.

Thanks for all of the help!

**Comment by Cruel** [comment]
You'll just have to wait until I add download options in settings. I'll allow you to increase timeout. Should give it more time to make http connection before giving up.

Probably won't get to adding that for a couple days.

**Comment by ThevishGeko07** [comment]
I see. Is there anyting I can do on my end while I wait for the update?

**Comment by Cruel** [comment]
The old freeShop versions will force an update, so don't think you can do much now.

**Comment by Cruel** [comment]
I increased default timeout from 5 to 8 seconds. Perhaps try version 2.0.3 to see if that helps at all.

**Comment by Cruel** [comment]
@ThevishGeko07 The latest update has some changes that should make things work even on pretty slow internet. You can go to Download settings and lower the buffer size, maybe try 32 KB.

**Comment by ThevishGeko07** [comment]
@Cruel Hi again, 
thanks so much for your work! It's working perfectly now since 2.1.1
