### ISSUE TITLE
Add prompt for deleting titles in 2.0

### ISSUE THREAD

**Issue by Chiharuuu** [Cruel/freeShop#84]
First off, awesome update as always. 

Was looking through my installed titles using the new menu in 2.0 (2.0.1), and somehow managed to tap the delete icon thing when I selected Animal Crossing New Leaf. 

Is there any chance for a prompt that asks if you wish you delete/asks for confirmation before deleting, in a future update? I'm now having to redownload the game and look to see if my save data is still there... I know it's my fault in a way, but just a suggestion for something that I think is needed.

**Comment by Cruel** [comment]
Yeah, I figured this may happen. Unfortunately, it likely removed savedata too. So I'll add this with higher priority, because I know you won't be the first.

**Comment by Chiharuuu** [comment]
Yup, it did remove savedata too. Luckily I still had a somewhat recent save backup so I was able to restore the save properly after reinstalling, and all is well.

**Comment by Cruel** [comment]
I added a delete confirmation screen in 2.0.3 so feel free to try it out and make sure it works properly.
