### ISSUE TITLE
Auto-update from versions <2.0 to 2.0.1 initializes cache improperly

### ISSUE THREAD

**Issue by Terathiel** [Cruel/freeShop#85]
I updated from 1.2.2 to 2.0.1 using freeShop's built in auto-update, and after successfully setting up title keys (double-checked) freeShop continued to insist that it could find no titles, suggesting I check my title keys or reinitialize the cache from settings, which is not implemented yet as far as I can tell. Deleting the new freeShop data folder and re-opening freeShop to properly initialize the cache worked.

**Comment by yarados** [comment]
hi! i do the same, my problem is that not title keys found. where can i find QR or URL?? help plase

**Comment by poutros** [comment]
@yarados Next time, don't post an issue about it.

**Comment by Cruel** [comment]
I'll need to add a "refresh cache" button. It is apparently not downloading/extracting properly for some people.

Also, I need to change the message to make it clearer. When no titles are listed, it's not necessarily because of the keys.
