### ISSUE TITLE
Download speeds go from ~700kbps to ~120kbps

### ISSUE THREAD

**Issue by reidrichardson** [Cruel/freeShop#87]
This happens to me when trying to download.  Is it something to do with the screen going to sleep?  

Just bought a 2DS yesterday for homebrew, just wanted to thank you for this awesome program as well.  This is insanely well done, you rock!

**Comment by poutros** [comment]
The 3ds's io is just horrible and so is it's network speed. Try seeing if this error occurs every time the screen goes to sleep.

**Comment by Cruel** [comment]
This is likely a speed fluctuation I cannot fix. For the o3ds, the max speed is around 750 KB/s, even if you have the best internet connection on earth.
