### ISSUE TITLE
Add retail cart and system titles (i.e. home menu) to game list when updates/DLC are available

### ISSUE THREAD

**Issue by RykenInverse** [Cruel/freeShop#88]
FreeShop has several titles that despite not being available themselves have their DLC available in the TitleKeys.bin, some of which (to the best of my understanding) are actually impossible to get Title Keys for due to being physical only, like the Special Edition release of Fire Emblem If that had both Byakuya and Anya included on the physical cart. Would it be feasible to add titles installed through means outside of FreeShop to the program's list of game software that appears under the bag-shaped tab to make it possible to acquire the DLC for said titles?

**Comment by RykenInverse** [comment]
>And @RykenInverse I'm not sure it will ever support DLC for titles when it doesn't have the main game title in cache. What will be done is that more titles need to be in cache. When most of them are there, it should be fine. I'm going to rewrite cache script soon to include most eShop games.

Understandably, though I fear that means that games that didn't get an eShop release at all would be SOL? i.e. Fire Emblem If's Special Edition, or the Premium Edition for Lost Heroes 2.

**Comment by Cruel** [comment]
Well actually, when I add the cart to be visible in the installed game list, I can probably pull icon/title from it fine. So now that I think about it, you will be able to put in a retail cart to install updates/DLC.

**Comment by RykenInverse** [comment]
That would be most wonderful. Good luck!

**Comment by metteemo** [comment]
If someone dumped their copy of Fire Emblem Fates Special Edition, then installed the game as a CIA, would the DLC content show up in Freeshop?

**Comment by RykenInverse** [comment]
You mean Fire Emblem If? If so, that Special Edition never got a digital release, and thus isn't on FreeShop's titlekey list at the moment, so no, the DLC content isn't downloadable at the moment. The entire reason I opened this issue is to address that, since between games like that and Lost Heroes 2 Premium, there's a few titles that it would not be possible to get DLC for through FreeShop unless games installed outside of FreeShop can be added to the in-program list of downloaded software. It seems that Cruel is planning to include this in the 2.2 release of FreeShop though.

**Comment by metteemo** [comment]
No, this: http://www.gamestop.com/nintendo-3ds/games/fire-emblem-fates-special-edition/126802 ... note the text "Only way to get all Three Versions on a Single Cartridge"

Fire Emblem If is the Japanese release, and has a different titlekey compared to the US release. The FE:F Special Edition is a US cartridge-only release, and I'm asking questions about how DLC would work for a CIA installed version of a dump of this cartridge.

**Comment by RykenInverse** [comment]
Ah, sounds like the same deal as the Special Edition for Fire Emblem If, so the issue is the same.
