### ISSUE TITLE
After every install, Failed to finalise content install : 0xD8E0806A

### ISSUE THREAD

**Issue by FerAsdev** [Cruel/freeShop#89]
Hello, the issue was after the recent update when I try install any game i get this error, "Failed to finalize content install: HEXCODE"

I have enought  free space in my SD and I'm using Luma CFW. I tryed reinstall the cia but it not works.

**Comment by Cruel** [comment]
Thanks for the report, but it would help to have the error code included.

Can you not install any game, like even a small one like 2048?

**Comment by FerAsdev** [comment]
Hi @Cruel,  this was the games that I tried isntall:

Double Dragon : Failed to finalize Content install: 0xD8E0806A
Donkey Kong Country 2: Failed to finalize Content install: 0xD8E0806A

Also I tried with small games like mr. game and watch  ~ 1.5 MB

The Hex Code error apparently is the same.

I've read that probably could be an SD card error so I formatted my sd but the problem persists.

This happens in my New 3DS, I will test in my Old 3DS. The Hex Code error apparently is the same,

**Comment by Cruel** [comment]
What is your CFW version?

**Comment by FerAsdev** [comment]
New 3DS, Firmware 11.0.0-33 U.
I tried with Luma v5.5 and Luma v6.01

Also I tested in the Old 3DS and it works perfectly with 11.0.0-33 U and Luma v5.5, it could be a N3DS problem ?

**Comment by Cruel** [comment]
Not likely a n3ds problem, but maybe. You try a different SD card (or the one that works on o3ds)?

**Comment by tommycv** [comment]
Don´t know if it still usefull, but i solved the same error by deleting the freeshop folder in the data folder, and uninstalling freeshop from the 3ds then installing the leatest build cia.

**Comment by lukecamilo** [comment]
I'm getting the exact same error for both games, DLCs and Updates. European n3ds with luma v6.01
I'll try what @tommycv said and i'll report back

**Comment by FerAsdev** [comment]
I´ve tried the @tommycv  solution but still not works, and I've checked my SD and is fine x__x is there a way to use an old version without auto update. I'm pretty sure that  the v1.2.2works fine in my N3DS

**Comment by Cruel** [comment]
@FerAsdev Where did you get your title key dump? Are you making sure to use "encTitleKeys" dump as opposed to the decrypted one?

**Comment by FerAsdev** [comment]
I get the keys from here [https://3ds.titlekeys.com/](url). the "encTitleKeys.bin" file. 

Tomorrow I will try format my 3ds and do a clean install of everything, I'll report back if it works. Anyways thanks alot for the support.

**Comment by FerAsdev** [comment]
Hi @Cruel finally the app has worked correctly.
For the information of all the people that have this issue, I  did the next steps:

1.- Delete all the freeEshop content from my SD, like @tommycv  sugested.
2.- Uninstall the app from the FBI Installer, choosing the option Delete Title and Ticket.
3.- Install the last version. 
4.- Load the titlekeys via QR from the new settings option from here [https://3ds.titlekeys.com/](url)
5.- Exit of the application
6.- And finally open again the app and has worked again.

@Cruel , thanks for the support, greetings.

**Comment by Cruel** [comment]
Thanks.

Very odd issue. I'll keep it open until it's understood why this happens and if this is a consistent solution.

**Comment by GlitchMC** [comment]
I followed @FerAsDev and uninstalled the title and key, and deleted the freeshop folder, reinstalled and whatnot. 
It seemed to have worked, but I can only download smaller titles. The one over a GB give a title install fail or tmd fail.

**Comment by Cruel** [comment]
@GlitchMC depending on the error code, sounds like you don't have enough space on SD card.

If you do have the space, you may want to look in FBI at the Pending Titles list. If you aren't currently installing titles in eShop or freeShop, this list should be empty. If it's not, then it means those titles were only partially install, and more importantly, their *entire* install size is reserved on the system so it can be completed. Clearly this list will make sure the system isn't reserving space you want to use.

**Comment by GlitchMC** [comment]
I have 24.1 GB free of a 32Gb sd card, and the Pending Titles list is empty [I had no idea what that list was supposed to be, but now I know, thanks :)]

**Comment by Cruel** [comment]
Then what error codes are you getting?

**Comment by GlitchMC** [comment]
Failed to finalize Tmd install: 0xF9608022
Failed to finalize title install: (I don't have the her code atm, let me see if I can get a title to fail)

**Comment by Cruel** [comment]
Yeah, I've never encountered 0xF9608022. What is your CFW setup? Luma? emunand?

**Comment by GlitchMC** [comment]
Luma 6.1.1 on n3DS Sys11. 0.0-33

**Comment by GlitchMC** [comment]
Failed to finalize Tmd install: 0xF9608022
**Edit**: Failed to finalize content install:0xD8E08025

Not-
Failed to finalize title install: (I don't have the her code atm, let me see if I can get a title to fail)

**Comment by Mamotromico** [comment]
I actually went through this and I just realized I was putting the incorrect URL for the titlekeys download

The clue was on @FerAsdev post

I was using the /download url from the 3ds.titlekeys website, and the correct url is /downloadenc

Thats why the QR code fixed this, it guarantess its using the correct url

**Comment by Cruel** [comment]
@GlitchMC or someone else, if you could please test was @Mamotromico said. Clear your /keys/ directory and make sure you're putting in the _encrypted_ keys there.

**Comment by GlitchMC** [comment]
So it turns out that the SD card I was using was a complete piece of garbage. I was having trouble with using it on my pc as well, so I bought a new SD card and have had no problems since then

**Comment by Cruel** [comment]
This was likely due to people use the wrong title keys (not the encrypted ones). If someone gets this issues even while using a encTitleKeys.bin dump, then I'll reopen the issue.
