### ISSUE TITLE
No Title Keys found?

### ISSUE THREAD

**Issue by ParadoxHereOK** [Cruel/freeShop#91]
it's said that,what i need to do? i can't understand this!

**Comment by THEDARKK** [comment]
Put an encTitleKeys.bin file in the directory sdmc:/3ds/data/freeShop/keys/

**Comment by poutros** [comment]
It means you need the title keys file. Search for `title keys site` on google and it should be the first one. Next, search for `Download encTitleKeys.bin`. Below it, there is a green symbol. Click it and scan it with freeshop.

**Comment by Cruel** [comment]
Yes, or use settings to set a URL to download for a key file dump.
