### ISSUE TITLE
No titles keys found. (update 1.1.2 to 2.0.1)

### ISSUE THREAD

**Issue by Foxystemn** [Cruel/freeShop#92]
my issue is this:

no title keys found.
make sure you have keys in
sdmc:/3ds/data/freeShop/keys/
Check settings to set up key
downloads or redownload cache

i tried many options and check another issues here and the my problem persist

**Comment by Cruel** [comment]
Did you put a key file manually in the directory or put a key file URL in settings?

**Comment by MikeModder** [comment]
Same problem. Tried both manually putting the file and having it auto download

**Comment by Cruel** [comment]
Well, it seems some people are having cache issues. I'll be putting in some fixes later today in an update.

For now, you should be able to solve this by deleting config.json and restarting freeShop to make it download cache. You'll lose saved settings, but there aren't many anyways.
