### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Ninjistix** [Cruel/freeShop#93]
1) ability to remember download queue (app crashes/freezes sometimes, when you re-enter the app download queue is empty)
2) auto retry failed downloads (notices sometimes titles over 1gb take awhile to dl and they error out after awhile)
3) to clear the search filed, eg. when searching for a title by inputting the name, won't go back to default list until you enter blank title.

**Comment by Ninjistix** [comment]
4) increase of download speed? (trying to dl 2gb file at 400kb's is a pain)
<img src="http://www.speedtest.net/result/5569882884.png" />

**Comment by Cruel** [comment]
1. Crashing means things don't exit properly and therefore cannot be saved. The queue saves without crashes, but the crashes need to be resolved.

3. For now, you can press B to reset search. I'll add something better later to reset search/filters.

4. Download speeds cannot be improved. On the o3ds, the max speed is around 750 KB/s. The eShop, and everything, has this hardware limitation. If you want, you can download using your PC, but then need to copy to your SD card and then install it.

**Comment by Ninjistix** [comment]
i'm on the N3DS

**Comment by Cruel** [comment]
Then you should be getting faster speeds unless Nintendo's server are temporarily slow.

**Comment by Ninjistix** [comment]
hey @Cruel would it be possible to add "remember" filters, so i dont have to keep going back and applying the USA region?

**Comment by Cruel** [comment]
Yeah, #64 will handle saving filters/sorting options.

And for your auto-retry suggestion, I don't think it's ideal. If there is an error in the download, that error should be fixed. Retrying will likely keep hitting same issue. Downloads shouldn't fail ideally.
