### ISSUE TITLE
System crashed when I install the DLC and updates

### ISSUE THREAD

**Issue by ITJesse** [Cruel/freeShop#95]
I have crashed twice when I install the DLC and update.

![img_0326](https://cloud.githubusercontent.com/assets/3601376/17852371/9fbc3994-6899-11e6-9439-4a25650ceef2.jpg)

[crash_dump_00000000.dmp.zip](https://github.com/Cruel/freeShop/files/429888/crash_dump_00000000.dmp.zip)

[crash_dump_00000001.dmp.zip](https://github.com/Cruel/freeShop/files/429887/crash_dump_00000001.dmp.zip)

**Comment by Cruel** [comment]
When you start the install or when it finishes?

**Comment by ITJesse** [comment]
When it Finishes.

**Comment by Cruel** [comment]
Ok, I think I know the issue. For me this happens open when the installed games list (shopping bag icon) is open. If I have anything else open, it's fine until I click on the shopping bag icon. Can you confirm this is the case for you too?

**Comment by ITJesse** [comment]
Yes you are right.
When I was seeing another game in the shopping bag, it crashed.

**Comment by Cruel** [comment]
Hey, can you test 2.0.3 to see if this is solved properly?

**Comment by ITJesse** [comment]
Fixed. Thanks!
