### ISSUE TITLE
failed to finalise content install : 0xD8E0806A

### ISSUE THREAD

**Issue by amirusan** [Cruel/freeShop#96]
Hi there,

Was told to post this on here. Happens on all titles I've tried so far. After download is complete it says failed to finalise content install : 0xD8E0806A.

Is this a known issue? If you want I can provide screenshots.

Thanks

**Comment by Ninjistix** [comment]
think this is related to issue #90

**Comment by Cruel** [comment]
No, it's a duplicate of #89

**Comment by amirusan** [comment]
Oh sorry Cruel, thanks for pointing that out.
