### ISSUE TITLE
Failed to finalise TMD install

### ISSUE THREAD

**Issue by smileyhead** [Cruel/freeShop#97]
I don't know if this issue occurs with any other games or not, but when I try to download Rayman 3D, I get this error:
Failed to finalise TMD install: 0xC86044D2

**Comment by Cruel** [comment]
I should add this error code to freeShop to avoid confusion.

This basically means you don't have enough space to install the game. Check the available space on your SD card.

**Comment by smileyhead** [comment]
I see.
Could you please add a Free Space Information page, then?

**Comment by Cruel** [comment]
Yeah, that is mentioned in #37
