### ISSUE TITLE
[Enhancement] Option to Make CIA + Save Config

### ISSUE THREAD

**Issue by SirBeethoven** [Cruel/freeShop#98]
Awesome job with this app! By the way, is there a way to port how CIAngel used to create CIA's too? Thank you! :) If this can be included in the settings, that would be awesome!!

Also, could FreeShop save its settings too? So you don't have to reapply them?

**Comment by Cruel** [comment]
I don't think I'll be adding CIA download on freeShop, see #61 

Also, #65 will address saving filter/sorting.
